services:
  gml.web.api:
    image: gml.web.api
    build:
      context: .
      dockerfile: src/Gml.WebApi/Dockerfile
    ports:
      - "5000:8080"
  gml.web.admin:
    image: gml.web.admin
    build:
      context: .
      dockerfile: src/Gml.Web.Panel/Dockerfile
    ports:
      - "5001:8081"
      - "5002:8082"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081;http://+:8082;
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
