services:
  filebrowser:
    image: filebrowser/filebrowser
    user: "${UID}:${GID}"
    environment:
      - FB_BASEURL=/filebrowser
    volumes:
      - shared_volume:/srv
      - /DATA_DIR:/data
      - /CONFIG_DIR:/config
    restart: always
    ports:
      - 5005:80
    networks:
      - gml-network

  gml-web-api:
    image: gml-web-api-image
    container_name: gml-web-api-container
    build:
      dockerfile: src/Gml.WebApi/Dockerfile
    volumes:
      - shared_volume:/home/app
    ports:
      - "5000:8080"
    networks:
      - gml-network

  gml-web-admin:
    image: gml-web-admin-image
    container_name: gml-web-admin-container
    build:
      context: .
      dockerfile: src/Gml.Web.Panel/Dockerfile
    ports:
      - "5003:8081"
      - "5004:8082"
    networks:
      - gml-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8081;http://+:8082;
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

networks:
  gml-network:
    name: gml-network
    attachable: true

volumes:
  shared_volume:
